### ISSUE TITLE
Getting an error message when a save is loaded

### ISSUE THREAD

**Issue by nickirk1984** [NeonOcean/S4.Cycle#2]
"Neon Ocean - Main: Major Saving Failure
One or more mods at least partially failed to load their save game data.
Offending saving identifiers:
NeonOcean_S4_Cycle_Save"

**Comment by NeonOcean** [comment]
I need a bit more information, can you follow this guide?
https://doc.mods.neonoceancreations.com/s4/cycle/general/reporting-bugs/index.html

**Comment by NeonOcean** [comment]
Please upload those log files as soon as you can.
I'm writing this message because I'm worried you might have missed my last one.

**Comment by nickirk1984** [comment]
Sorry, busy with work. It doesn't show up as a Last Exception error in the game, so there's no log of it in the Sims folder (as far as I know). It also happens seemingly at random. I'll load a save and then load a household and it's fine. But then I'll switch households or travel with a Sim and the error happens. And when it does, it resets the Sim's cycle and delete's the tracking app from their phone and I have to re-download it.

**Comment by NeonOcean** [comment]
The mod should make it's own logs. You should be able to get Cycle's logs by going to your Sims 4 folder, then NeonOcean > Debug > Mods > NeonOcean.S4.Cycle. 

Please send the entire folder named "NeonOcean" to a zip file and attach it here.

**Comment by nickirk1984** [comment]
[NeonOcean copy.zip](https://github.com/NeonOcean/S4.Cycle/files/4842851/NeonOcean.copy.zip)

**Comment by NeonOcean** [comment]
Okay, I've figured out why this notification appears. It has to do with the mod being unable to load whether or not you have told a sim to not use condoms. Try just taking the condoms out of the sim's inventory instead, until I can release another update.

The message is just caused by a minor issue and doesn't have to do with the cycle resetting and the tracking app being deleted, this is a separate problem. Are you sure that the sim's cycle had reset? I'm thinking that the sim's actual cycle probably didn't reset, just installation state and where the app thinks the sim is at in their cycle did.

**Comment by NeonOcean** [comment]
I believe I have solved these issues with the latest update, please reopen this issue if you still experience problems with your sim's cycles resetting.
